config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/urls.py
from django.urls import path

from todo.views import (
    TaskListView,
    TaskDetailView,
    TagListView,
    TagDetailView,
    TaskCreateView,
    TaskUpdateView,
    TagUpdateView,
    TagCreateView,
    TaskDeleteView,
    TagDeleteView,
    do_task_view,
    undo_task_view,
    DoneTaskListView,
    UnDoneTaskListView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("done/", DoneTaskListView.as_view(), name="task-done"),
    path("undone/", UnDoneTaskListView.as_view(), name="task-undone"),
    path("<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/do/", do_task_view, name="task-do"),
    path("<int:pk>/undo/", undo_task_view, name="task-undo"),
    path("task-create/", TaskCreateView.as_view(), name="task-create"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag-detail"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo"

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ("is_done", "-created_at")

todo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from todo.models import Tag, Task


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "deadline": forms.TextInput(attrs={"type": "datetime-local"}),
        }

    def clean_deadline(self):
        deadline = self.cleaned_data.get("deadline")
        now = timezone.now()

        if deadline and deadline < now:
            raise ValidationError("Deadline must be not less than current date")

        return deadline


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"

todo/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from .forms import TaskForm, TagForm
from .models import Task, Tag


class TaskListView(generic.ListView):
    model = Task

    def get_queryset(self):
        return Task.objects.prefetch_related("tags")


class DoneTaskListView(generic.ListView):
    model = Task
    template_name = "todo/task_list.html"

    def get_queryset(self):
        return Task.objects.prefetch_related("tags").filter(is_done=True)


class UnDoneTaskListView(generic.ListView):
    model = Task
    template_name = "todo/task_list.html"

    def get_queryset(self):
        return Task.objects.prefetch_related("tags").filter(is_done=False)


class TaskDetailView(generic.DetailView):
    model = Task

    def get_queryset(self):
        return Task.objects.prefetch_related("tags")


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


def do_task_view(request: HttpRequest, pk: int) -> HttpResponse:
    task = get_object_or_404(Task, pk=pk)
    task.is_done = True
    task.save()
    return redirect(request.META.get("HTTP_REFERER"))


def undo_task_view(request: HttpRequest, pk: int) -> HttpResponse:
    task = get_object_or_404(Task, pk=pk)
    task.is_done = False
    task.save()
    return redirect(request.META.get("HTTP_REFERER"))


class TagListView(generic.ListView):
    model = Tag


class TagDetailView(generic.DetailView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    template_name = "todo/tag_form.html"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    template_name = "todo/tag_form.html"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <title>
    {% block title %}

    {% endblock %}

  </title>
</head>
<body>
  <div class="container-fluid">
  <div class="row">
    {% include "include/sidebar.html" %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      {% block content %}
      {% endblock %}
    </main>
  </div>
</div>
</body>
</html>

templates/include/sidebar.html
<nav class="col-md-2 d-none d-md-block bg-light sidebar" style="height: 100vh; padding-top: 100px">
  <div class="sidebar-sticky text-center">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'todo:index' %}">
          <i class="fas fa-home mr-2"></i> Home
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'todo:tag-list' %}">
          <i class="fas fa-tags mr-2"></i> All Tags
        </a>
      </li>
      <br>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'todo:task-done' %}">
          <i class="fas fa-tags mr-2"></i> Done Tasks
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'todo:task-undone' %}">
          <i class="fas fa-tags mr-2"></i> Undone Tasks
        </a>
      </li>
    </ul>
  </div>
</nav>

templates/todo/tag_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <h2>Confirm Delete Tag</h2>
    <p>Are you sure you want to delete the tag "{{ tag.name }}"?</p>
    <form method="POST" action="">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Confirm Delete</button>
      <a href="{% url 'todo:tag-list' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/todo/tag_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <h1>Tag Detail</h1>
    <div class="mt-4">
      <h3>{{ tag.name }}</h3>
      <p>
        <strong>Tasks:</strong>
        {% for task in tag.tasks.all %}
          <span class="badge badge-info"><a href="{% url 'todo:task-detail' pk=task.id %}">{{ task.content }}</a></span>
        {% endfor %}
      </p>
      <div class="btn-group" role="group" aria-label="Tag Actions">
        <a class="btn btn-info" href="{% url 'todo:tag-update' pk=tag.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'todo:tag-delete' pk=tag.id %}">Delete</a>
      </div>
    </div>
  </div>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form method="POST" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-8">
        <h1>Tags</h1>
      </div>
      <div class="col-md-4 text-right">
        <a class="btn btn-primary" href="{% url 'todo:tag-create' %}">Add Tag</a>
      </div>
    </div>
    <hr>

    <table class="table mt-3">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Update</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for tag in tag_list %}
          <tr>
            <td>
              <a href="{% url 'todo:tag-detail' pk=tag.id %}">{{ tag.name }}</a>
            </td>
            <td>
              <a class="btn btn-info btn-sm" href="{% url 'todo:tag-update' pk=tag.id %}">Update</a>
            </td>
            <td>
              <a class="btn btn-danger btn-sm" href="{% url 'todo:tag-delete' pk=tag.id %}">Delete</a>
            </td>
          </tr>
          {% empty %}
      <h1>There are to tasks yet!</h1>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <h2>Confirm Delete Task</h2>
    <p>Are you sure you want to delete the task "{{ task.content }}"?</p>
    <form method="POST" action="">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Confirm Delete</button>
      <a href="{% url 'todo:index' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/todo/task_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <h1>Task Detail</h1>
    <div class="mt-4">
      <h5>{{ task.content }}</h5>
      <p>
        {% if task.is_done == True %}
          <span class="text-success">Done</span>
        {% else %}
          <span class="task-danger">Not done</span>
        {% endif %}
        <br>
        <strong>Deadline:</strong> {{ task.deadline }}
        <br>
        <strong>Created at:</strong> {{ task.created_at }}
        <br>
        <strong>Tags:</strong>
        {% for tag in task.tags.all %}
          <span class="badge badge-info"><a href="{% url 'todo:tag-detail' pk=tag.id %}">{{ tag.name }}</a></span>
        {% endfor %}
      </p>
      <div class="btn-group" role="group" aria-label="Task Actions">
        <a class="btn btn-primary" href="{% url 'todo:task-update' pk=task.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'todo:task-delete' pk=task.id %}">Delete</a>
      </div>
    </div>
  </div>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form method="POST" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="mb-0">TODO list:</h1>
      <a class="btn btn-primary" href="{% url 'todo:task-create' %}">Add task</a>
    </div>

    <hr>

    {% for task in task_list %}
      <div class="card mb-3">
        <div class="card-body">
           {% if task.is_done == False %}
            <div class="d-flex justify-content-between align-items-center">
              <h5 class="card-title"><a href="{% url 'todo:task-detail' pk=task.id %}">{{ task.content }}</a></h5>
              <a href="{% url 'todo:task-do' pk=task.id %}" class="btn btn-success">Complete</a>
            </div>
          <p class="card-text">
              <span class="text-danger">Not done</span>
              <br>
              <span>Deadline: {{ task.deadline }}</span>
            {% else %}
             <div class="d-flex justify-content-between align-items-center">
              <h5 class="card-title"><a href="{% url 'todo:task-detail' pk=task.id %}">{{ task.content }}</a></h5>
              <a href="{% url 'todo:task-undo' pk=task.id %}" class="btn btn-danger">Undo</a>
            </div>
              <span class="text-success">Done</span>
            {% endif %}
            <br>
            <span>Created at: {{ task.created_at }}</span>
            <br>
            <strong>Tags:</strong>
            {% for tag in task.tags.all %}
              <span class="badge badge-info"><a href="{% url 'todo:tag-detail' pk=tag.id %}">{{ tag.name }}</a></span>
            {% endfor %}
          </p>
          <div class="btn-group" role="group" aria-label="Task Actions">
            <a class="btn btn-primary btn-sm" href="{% url 'todo:task-update' pk=task.id %}">Update</a>
            <a class="btn btn-danger btn-sm" href="{% url 'todo:task-delete' pk=task.id %}">Delete</a>
          </div>
        </div>
      </div>
      {% empty %}
      <h1>There are to tasks yet!</h1>
    {% endfor %}
  </div>
{% endblock %}